[package]
name = "image_optimiser"
version = "0.1.0"
edition = "2021"

[dependencies]
pcre2 = "0.2.9"
serde = { version = "1.0", features = ["derive"] }
urlencoding = "2.1.3"
http-client = "6.5.3"
image = "0.25.5"
tokio = { version = "1", features = ["full"] }
wasm-bindgen = "0.2.100"